### PR TITLE
make the UMD build apply globals as expected

### PR DESCRIPTION
**Pull request by trusktr**
useful for including the polyfill as a script tag

### CODE REVIEW

**Comment by trusktr** [comment]
Good to go, the additional `extend: true` option made it work.

**Comment by TremayneChrist** [comment]
Thanks for this @trusktr. I'll check it out!

**Comment by TremayneChrist** [comment]
All looks great, thanks @trusktr. The only issue with this is that it is a breaking change for people using the current UMD build.

**Comment by TremayneChrist** [comment]
Is this something that you're waiting on? Just thinking this could be placed in the v4 release.

**Pull request merged**
